name: Check SL

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Check 
        id: checker
        run: |
            curl https://invest.swisslife-am.com -o curl-output

      - name: Create Issue From File
        if: ${{ steps.checker.outputs.exit_code != 0 }}
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: SL Link check failed!
          content-filepath: curl-output
          labels: report, automated issue